spring:
  application:
    name: security-token
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security-token
    username: fallou
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update  # or 'validate', 'create', 'create-drop'
    properties:
      hibernate:
        default_schema: security-token  # 👈 set your schema name here


jwt:
  token:
    secret: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    expiration: 86400000      # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds